### ISSUE TITLE
Color Override

### ISSUE THREAD

**Issue by toastal** [pukkamustard/elm-identicon#4]
I know Identicons generate their own colors by default, but it would be nice to have a version where I could pass in either a `Color` or a `String` to override that. If that's okay and you don't have time, I can even do the code/PR.

Side note:
https://github.com/pukkamustard/elm-identicon/blob/master/src/Identicon.elm#L31-L32 could be `List.range 0 14`.

**Comment by pukkamustard** [comment]
Yes, sure.

How about a function `custom`:
```
custom : (String -> Int) -> (String -> Color) -> String -> H.Html msg
```

such that `identicon` is:
```
identicon =
    custom computeHash identicolor
```

In order to use the same hash `computeHash` needs to be exported. Maybe rename it `defaultHash`? Then also rename `identicolor` to `defaultColor`?

Could you do the code/PR?

**Comment by toastal** [comment]
Feel free to merge and readjust and change the documentation words

**Comment by toastal** [comment]
Ah... I missed something.

**Comment by pukkamustard** [comment]
#5 merged. Thank you!
